name: emcus_sathishkumar_r
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase Core (required to initialize Firebase)
  firebase_core: ^3.13.0

  # Firebase Authentication
  firebase_auth: ^5.5.2

  # BLoC for state management
  flutter_bloc: ^9.1.0

  # Dependency Injection
  get_it: ^8.0.3
  
  dartz: ^0.10.1
  cloud_firestore: ^5.6.6
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/

  fonts:
    - family: Humanst521BT
      fonts:
        - asset: fonts/Humanist521BoldBT.ttf
        - asset: fonts/Humanst521BT.ttf

    - family: Inter
      fonts:
        - asset: fonts/Inter_24pt-Black.ttf
        - asset: fonts/Inter_24pt-Bold.ttf
        - asset: fonts/Inter_24pt-ExtraBold.ttf
        - asset: fonts/Inter_24pt-Light.ttf
        - asset: fonts/Inter_24pt-Medium.ttf
        - asset: fonts/Inter_24pt-Regular.ttf
        - asset: fonts/Inter_24pt-SemiBold.ttf
     
